version: '2'

services:
  app:
    build: ./app
    # restart: always

  elasticsearch:
    image: elasticsearch
    command: elasticsearch
    expose:
      - "9200"
      - "9300"
    volumes:
      - "/tmp/esdata:/usr/share/elasticsearch/data"
